### ISSUE TITLE
Kanji missing from JIS set

### ISSUE THREAD

**Issue by aaronbell** [satsuyako/Hina-Mincho#2]
It appears that many Kanji glyphs in the JIS 1 / JIS 2 set are empty. 
<img width="517" alt="Screen Shot 2020-12-04 at 2 12 26 PM" src="https://user-images.githubusercontent.com/8460297/101220622-db4a1300-363a-11eb-8fcc-9ab4e06efa0e.png">

Is this an older version of the file? Can you review? 

Thanks

**Comment by satsuyako** [comment]
I am sorry for the delay in my response and thank you for waiting.
I uproaded the completed data.

Please let me know if there are any problems.
<img width="1511" alt="スクリーンショット 2021-02-04 12 04 07" src="https://user-images.githubusercontent.com/54973107/106839347-6306d900-66e1-11eb-9a52-e4a4a59b5045.png">

**Comment by aaronbell** [comment]
Thank you! :)
